# Use the checked-in compilation, but replace its reference CPU-runtime section
# with the notices from the SDK actually selected for this build.
set(RENDEPTH_LEGAL_OUTPUT_DIR "${CMAKE_BINARY_DIR}/generated/Legal")
file(MAKE_DIRECTORY "${RENDEPTH_LEGAL_OUTPUT_DIR}")
configure_file("${CMAKE_SOURCE_DIR}/Legal/RENDEPTH_APP_LICENSE"
    "${RENDEPTH_LEGAL_OUTPUT_DIR}/RENDEPTH_APP_LICENSE" COPYONLY)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${CMAKE_SOURCE_DIR}/Legal/THIRD_PARTY_LICENSING")
file(READ "${CMAKE_SOURCE_DIR}/Legal/THIRD_PARTY_LICENSING" RENDEPTH_LEGAL_NOTICES)
set(RENDEPTH_RUNTIME_NOTICE_MARKER "=== CONFIGURED ONNX RUNTIME NOTICES ===")
string(FIND "${RENDEPTH_LEGAL_NOTICES}" "${RENDEPTH_RUNTIME_NOTICE_MARKER}" RENDEPTH_RUNTIME_NOTICE_OFFSET)
if(RENDEPTH_RUNTIME_NOTICE_OFFSET LESS 0)
    message(FATAL_ERROR "Regenerate Legal/THIRD_PARTY_LICENSING with Tools/update_legal_notices.py")
endif()
string(SUBSTRING "${RENDEPTH_LEGAL_NOTICES}" 0 ${RENDEPTH_RUNTIME_NOTICE_OFFSET} RENDEPTH_LEGAL_NOTICES)
string(APPEND RENDEPTH_LEGAL_NOTICES "${RENDEPTH_RUNTIME_NOTICE_MARKER}\n")
if(RENDEPTH_ENABLE_ONNX_RUNTIME)
    string(APPEND RENDEPTH_LEGAL_NOTICES "Source repository: https://github.com/microsoft/onnxruntime\n")
    if(WIN32)
        set(RENDEPTH_LEGAL_RUNTIME_DIR "${RENDEPTH_CPU_RUNTIME_DIR}")
    elseif(APPLE)
        set(RENDEPTH_LEGAL_RUNTIME_DIR "${RENDEPTH_ONNXRUNTIME_DIR}")
    else()
        set(RENDEPTH_LEGAL_RUNTIME_DIR "${RENDEPTH_CPU_RUNTIME_NOTICES_DIR}")
    endif()
    foreach(notice VERSION_NUMBER GIT_COMMIT_ID LICENSE ThirdPartyNotices.txt)
        set(notice_file "${RENDEPTH_LEGAL_RUNTIME_DIR}/${notice}")
        if(NOT EXISTS "${notice_file}")
            if(notice STREQUAL "LICENSE" OR notice STREQUAL "ThirdPartyNotices.txt")
                message(FATAL_ERROR "The selected ONNX Runtime SDK must contain ${notice}")
            endif()
            continue()
        endif()
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${notice_file}")
        file(READ "${notice_file}" notice_text)
        if(notice STREQUAL "GIT_COMMIT_ID")
            string(STRIP "${notice_text}" runtime_revision)
            if(runtime_revision MATCHES "^[0-9a-fA-F]+$")
                string(APPEND RENDEPTH_LEGAL_NOTICES
                    "Reference source: https://github.com/microsoft/onnxruntime/tree/${runtime_revision}\n")
            endif()
        endif()
        file(SHA256 "${notice_file}" notice_hash)
        string(APPEND RENDEPTH_LEGAL_NOTICES
            "\n--- ONNX Runtime ${notice} ---\nSource: configured CPU runtime SDK/${notice}\nSource SHA-256: ${notice_hash}\n\n${notice_text}\n")
    endforeach()
else()
    string(APPEND RENDEPTH_LEGAL_NOTICES "ONNX Runtime is disabled in this build.\n")
endif()
file(WRITE "${RENDEPTH_LEGAL_OUTPUT_DIR}/THIRD_PARTY_LICENSING" "${RENDEPTH_LEGAL_NOTICES}")
